project:
  type: website
  output-dir: docs

website:
  title: "Katie Donnelly"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Services"
        href: services.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: true